### ISSUE TITLE
Может лучше использовать Terraform или Vagrant?

### ISSUE THREAD

**Issue by 3ayazaya** [koptev-vit/VMWareDiplom#1]
[Terraform](https://www.hashicorp.com/products/terraform) - создание инфраструктуры
[Vagrant](https://www.vagrantup.com/) - создание ВМ и конфигурирование виртуальной среды

**Comment by koptev-vit** [comment]
Может быть, пока только подбираю, думал на ansible ещё, но как-то шелл зашёл больше, посмотрю и твои варианты сегодня)
